node {

    checkout scm

    docker.withRegistry('https://hub.docker.com/repositories', 'babansoumya') {

        def customImage = docker.build("babansoumya/dockerwebapp")

        /* Push the container to the custom Registry */
        customImage.push()
    }
}